// FONTE DE IMPORTAÇÃO LEGADA — NÃO É CONSULTADO PELO JOGO EM RUNTIME.
//
// Estes 1.069 registros são preservados para permitir reimportação.
// O importador seguro (scripts/import-overall-manual.mjs) transforma as
// entradas em registros persistentes year + player_id no Supabase.
// Nunca edite este arquivo esperando alterar o jogo diretamente.
//
// Correspondências ambíguas ou ausentes não são importadas automaticamente.
// Para corrigir uma associação, use o painel Admin ou
// data/overall-manual-associations.json.

export const OVERALL_MANUAL: Record<number, Record<string, number>> = {
  1930: {
    "Enrique Ballesteros": 82,
    "José Leandro Andrade": 90,
    "José Nasazzi": 88,
    "Ángel Bossio": 83,
    "José María Lavalle": 86,
    "Pedro Cea": 87,
    "Pedro Petrone": 86,
    "Héctor Castro": 86,
    "Juan Carlos Calvo": 85,
    "Pablo Dorado": 84,
    "Pedro Benítez": 84,
    "José Della Torre": 85,
    "Juan Evaristo": 83,
    "Luis Monti": 89,
    "Carlos Peucelle": 88,
    "Guillermo Stábile": 92,
    "Manuel Ferreira": 87,
    "Francisco Varallo": 90,
    "Joel": 78,
    "Brilhante": 80,
    "Itália": 79,
    "Fausto": 86,
    "Fernando": 82,
    "Carvalho Leite": 83,
    "Preguinho": 85,
    "Nilo": 81,
    "Moderato": 80,
    "Benedicto": 79,
    "Oswaldo Gomes": 78
  },
  1934: {
    "Gianpiero Combi": 86,
    "Luigi Allemandi": 87,
    "Raimundo Orsi": 88,
    "Luigi Bertolini": 84,
    "Enrique Guaita": 86,
    "Giuseppe Meazza": 93,
    "Angelo Schiavio": 90,
    "Attilio Demaría": 84,
    "Leopoldo Conti": 85,
    "Willibald Kreß": 83,
    "Paul Janes": 85,
    "Jakob Bender": 83,
    "Reinhold Münzenberg": 86,
    "Edmund Conen": 85,
    "Rudolf Gramlich": 82,
    "Fritz Szepan": 87,
    "Karl Hohmann": 86,
    "Stanislaus Kobierski": 83,
    "Ricardo Zamora": 90,
    "Jacinto Quincoces": 87,
    "Ciriaco": 84,
    "José Muguerza": 83,
    "Martín Marculeta": 85,
    "Isidro Lángara": 89,
    "José Nehin": 87,
    "Ramón Astudillo": 82,
    "Eduardo González Valiño": 84,
    "František Plánička": 91,
    "Josef Čtyřoký": 84,
    "Josef Streb": 83,
    "Josef Košťálek": 86,
    "Oldřich Nejedlý": 92,
    "František Svoboda": 85,
    "Antonín Puč": 86,
    "František Junek": 84,
    "Antal Szabó": 85,
    "József Háda": 83,
    "Sándor Bíró": 85,
    "György Sárosi": 91,
    "János Dudás": 87,
    "Gyula Futó": 82
  },
  1938: {
    "Aldo Olivieri": 87,
    "Alfredo Foni": 85,
    "Pietro Rava": 86,
    "Annibale Frossi": 88,
    "Giuseppe Meazza": 92,
    "Giovanni Ferrari": 86,
    "Ugo Locatelli": 87,
    "Pietro Serantoni": 85,
    "Renato Olmi": 84,
    "Sergio Bertoni": 84,
    "Batatais": 82,
    "Domingos da Guia": 90,
    "Machado": 85,
    "Afonsinho": 84,
    "Martim": 83,
    "Zezé Procópio": 86,
    "Leônidas": 94,
    "Romeu": 87,
    "Elba de Pádua Lima": 88,
    "Perácio": 89,
    "Patesko": 85,
    "Antal Szabó": 85,
    "József Háda": 86,
    "Gyula Polgár": 86,
    "György Sárosi": 93,
    "Gyula Zsengellér": 91,
    "József Turay": 88,
    "János Dudás": 84,
    "František Plánička": 85,
    "Josef Gauchel": 84,
    "Josef Košťálek": 88,
    "Oldřich Nejedlý": 93,
    "Antonín Puč": 87
  },
  1950: {
    "Barbosa": 86,
    "Augusto": 84,
    "Juvenal": 85,
    "Bauer": 88,
    "Danilo": 87,
    "Rodrigues": 83,
    "Friaça": 86,
    "Zizinho": 94,
    "Ademir": 93,
    "Jair": 89,
    "Francisco Urroz": 88,
    "Roque Máspoli": 85,
    "Juan Carlos González": 84,
    "Matías González": 83,
    "Obdulio Varela": 92,
    "Víctor Rodríguez Andrade": 86,
    "Juan Alberto Schiaffino": 94,
    "Alcides Ghiggia": 93,
    "Oscar Míguez": 90
  },
  1954: {
    "Toni Turek": 88,
    "Karl-Heinz Metzner": 86,
    "Werner Liebrich": 85,
    "Horst Eckel": 84,
    "Josef Posipal": 87,
    "Werner Kohlmeyer": 83,
    "Helmut Rahn": 88,
    "Max Morlock": 89,
    "Ottmar Walter": 90,
    "Fritz Walter": 93,
    "Gyula Grosics": 91,
    "Jenő Buzánszky": 88,
    "József Bozsik": 93,
    "Gyula Lóránt": 90,
    "Mihály Lantos": 87,
    "József Zakariás": 88,
    "László Budai": 89,
    "Sándor Kocsis": 94,
    "Ferenc Puskás": 96,
    "Zoltán Czibor": 92,
    "Nándor Hidegkuti": 95,
    "Carlos José Castilho": 87,
    "Djalma Santos": 90,
    "Nílton Santos": 91,
    "Bauer": 89,
    "Pinheiro": 85,
    "Julinho": 92,
    "Valdir Pereira": 93,
    "Baltazar": 88,
    "Rodrigues": 84,
    "Maurinho": 86,
    "Roque Máspoli": 86,
    "Juan Gómez": 85,
    "Obdulio Varela": 91,
    "Víctor Rodríguez Andrade": 87,
    "Juan Alberto Schiaffino": 93,
    "Oscar Míguez": 89,
    "Javier Ambrois": 84,
    "Luis Cruz": 84
  },
  1958: {
    "Gilmar": 90,
    "Djalma Santos": 92,
    "Hilderaldo Bellini": 91,
    "Orlando": 88,
    "Nílton Santos": 93,
    "Zito": 90,
    "Valdir Pereira": 94,
    "Garrincha": 96,
    "Vavá": 92,
    "Pelé": 97,
    "Mário Zagallo": 91,
    "Heinz Kwiatkowski": 85,
    "Josef Hamerl": 88,
    "Horst Szymaniak": 87,
    "Horst Eckel": 86,
    "Aki Schmidt": 84,
    "Werner Mai": 85,
    "Helmut Rahn": 89,
    "Uwe Seeler": 92,
    "Fritz Walter": 90,
    "Robert Jonquet": 88,
    "Jean-Jacques Marcel": 86,
    "Roger Piantoni": 89,
    "Just Fontaine": 95,
    "Jean Vincent": 88,
    "Maryan Wisnieski": 87,
    "Robert Dienst": 86,
    "Claude Abbes": 85,
    "Dominique Colonna": 85,
    "François Remetter": 84,
    "Kalle Svensson": 86,
    "Orvar Bergmark": 88,
    "Sven Axbom": 87,
    "Sigge Parling": 85,
    "Nils Liedholm": 92,
    "Kurt Hamrin": 90,
    "Agne Simonsson": 89,
    "Karl Koller": 86,
    "Gunnar Gren": 88,
    "Bengt Gustavsson": 86
  },
  1998: {
    "Cláudio Taffarel": 94,
    "Cafu": 94,
    "Aldair": 92,
    "Tab Ramos": 86,
    "Roberto Carlos": 95,
    "César Sampaio": 89,
    "Dunga": 91,
    "Rivaldo": 94,
    "Leonardo": 91,
    "Ronaldo": 85,
    "Joseph N'Do": 87,
    "Carlos Roa": 91,
    "Javier Zanetti": 94,
    "Roberto Ayala": 92,
    "José Chamot": 89,
    "Roberto Néstor Sensini": 88,
    "Diego Simeone": 92,
    "Matías Almeyda": 88,
    "Juan Sebastián Verón": 91,
    "Claudio López": 90,
    "Gabriel Batistuta": 95,
    "Ariel Ortega": 92,
    "Fabien Barthez": 93,
    "Lilian Thuram": 94,
    "Marcel Desailly": 94,
    "Frank Leboeuf": 88,
    "Bixente Lizarazu": 92,
    "Didier Deschamps": 93,
    "Patrick Vieira": 91,
    "Zinedine Zidane": 96,
    "Youri Djorkaeff": 92,
    "Thierry Henry": 89,
    "Christophe Dugarry": 87,
    "Edwin van der Sar": 93,
    "Michael Reiziger": 88,
    "Jaap Stam": 91,
    "Frank de Boer": 94,
    "Arthur Numan": 89,
    "Edgar Davids": 93,
    "Ronald de Boer": 91,
    "Phillip Cocu": 89,
    "Marc Overmars": 94,
    "Patrick Kluivert": 92,
    "Dennis Bergkamp": 96,
    "Peter Schmeichel": 94,
    "Henrik Andersen": 86,
    "Marc Rieper": 90,
    "Jes Høgh": 88,
    "Thomas Helveg": 89,
    "Thomas Helmer": 85,
    "Michael Laudrup": 93,
    "Brian Laudrup": 94,
    "Martin Jørgensen": 87,
    "Ebbe Sand": 88,
    "Per Frandsen": 84,
    "José Luis Chilavert": 95,
    "Francisco Arce": 90,
    "Carlos Gamarra": 94,
    "Celso Ayala": 88,
    "Roberto Acuña": 89,
    "José Cardozo": 94,
    "Julio César Enciso": 86,
    "Denis Caniza": 87,
    "Jorge Campos": 90,
    "Claudio Suárez": 92,
    "Duilio Davino": 87,
    "Rafael Alkorta": 86,
    "Ramón Ramírez": 91,
    "Alberto García Aspe": 90,
    "Pável Pardo": 87,
    "Jesús Arellano": 89,
    "Cuauhtémoc Blanco": 91,
    "Luis Hernández": 93,
    "Francisco Palencia": 86,
    "Fernando Hierro": 94,
    "Raúl": 92,
    "Fernando Morientes": 89,
    "Gaizka Mendieta Zabala": 90,
    "Alfonso": 88,
    "Joseba Etxeberria": 87,
    "Roberto Baggio": 94
  },
  2002: {
    "Marcos": 91,
    "Cafu": 94,
    "Lúcio": 91,
    "Roque Júnior": 88,
    "Roberto Carlos": 95,
    "Gilberto Silva": 89,
    "Juninho Paulista": 88,
    "Ronaldo": 98,
    "Rivaldo": 96,
    "Edílson": 87,
    "Pablo Cavallero": 87,
    "Javier Zanetti": 78,
    "Roberto Ayala": 94,
    "Walter Samuel": 91,
    "Juan Pablo Sorín": 92,
    "Javier de Pedro": 89,
    "Diego Simeone": 89,
    "Juan Sebastián Verón": 92,
    "Claudio López": 90,
    "Gabriel Batistuta": 94,
    "Hernán Crespo": 92,
    "Gianluigi Buffon": 95,
    "Christian Panucci": 89,
    "Alessandro Nesta": 94,
    "Fabio Cannavaro": 93,
    "Paolo Maldini": 95,
    "Luigi Di Biagio": 88,
    "Francesco Totti": 94,
    "Marco Delvecchio": 86,
    "Filippo Inzaghi": 91,
    "Alessandro Del Piero": 93,
    "Christian Vieri": 95,
    "Oliver Kahn": 96,
    "Thomas Linke": 88,
    "Carsten Ramelow": 87,
    "Christoph Metzelder": 85,
    "Michael Ballack": 87,
    "Bernd Schneider": 89,
    "Torsten Frings": 88,
    "Marco Bode": 87,
    "Miroslav Klose": 89,
    "Oliver Neuville": 88,
    "Claudio Miguel Pizarro Bosio": 87,
    "Fabien Barthez": 91,
    "Lilian Thuram": 92,
    "Marcel Desailly": 92,
    "Frank Leboeuf": 87,
    "Bixente Lizarazu": 90,
    "Patrick Vieira": 94,
    "Claude Makélélé": 88,
    "Zinedine Zidane": 94,
    "Robert Prosinečki": 91,
    "Thierry Henry": 94,
    "David Trezeguet": 93,
    "Edwin Tenorio": 92,
    "Frank Baumann": 91,
    "Steven Pienaar": 92,
    "Patrick M'Boma": 90,
    "Rio Ferdinand": 84,
    "Ricardo": 90,
    "Jorge Costa": 91,
    "Fernando Couto": 92,
    "Abel Fernando Moreira Ferreira": 87,
    "Nuno Miguel Ribeiro de Oliveira Valente": 88,
    "Rui Costa": 94,
    "João Pinto": 89,
    "Luís Figo": 96,
    "Pedro Miguel Carreiro Resendes": 90,
    "José Luis Chilavert": 94,
    "Carlos Gamarra": 92,
    "Celso Ayala": 89,
    "Denis Caniza": 87,
    "Francisco Arce": 88,
    "Roberto Acuña": 89,
    "Julio César Cáceres": 85,
    "José Cardozo": 94,
    "Roque Santa Cruz": 86,
    "Delio César Toledo": 87,
    "Jorge Campos": 86,
    "Rafael Márquez": 91,
    "Duilio César Davino Rodríguez": 86,
    "Salvador Carmona": 85,
    "Pável Pardo Segura": 88,
    "Gerardo Torrado": 87,
    "Cuauhtémoc Blanco": 89,
    "Jared Borgetti": 92,
    "Jesús Arellano": 88,
    "Rüştü Reçber": 94,
    "Fatih Akyel": 87,
    "Alpay Özalan": 90,
    "Bülent Korkmaz": 91,
    "Ümit Davala": 88,
    "Emre Belözoğlu": 87,
    "Yıldıray Baştürk": 91,
    "Hasan Şaş": 91,
    "Hakan Şükür": 93,
    "İlhan Mansız": 89,
    "Okan Buruk": 87,
    "Ergün Penbe": 87,
    "Ogün Temizkanoğlu": 87,
    "Oğuz Çetin": 88,
    "Sergen Yalçın": 87,
    "Arif Erdem": 88,
    "Tayfur Havutçu": 85,
    "Iker Casillas": 93,
    "Carles Puyol": 91,
    "Fernando Hierro": 91,
    "Ángel Fernández": 88,
    "Rafael García": 86,
    "Xavi": 85,
    "Gaizka Mendieta": 89,
    "Joaquín": 87,
    "Raúl": 95,
    "Fernando Morientes": 92,
    "Diego Tristán": 89
  },
  2006: {
    "Jens Lehmann": 92,
    "Oliver Kahn": 90,
    "Philipp Lahm": 91,
    "Christoph Metzelder": 88,
    "Per Mertesacker": 87,
    "Arne Friedrich": 87,
    "Michael Ballack": 94,
    "Torsten Frings": 91,
    "Bastian Schweinsteiger": 88,
    "Bernd Schneider": 89,
    "Miroslav Klose": 95,
    "Lukas Podolski": 91,
    "Roberto Abbondanzieri": 90,
    "Roberto Ayala": 92,
    "Gabriel Heinze": 91,
    "Fabricio Coloccini": 86,
    "Javier Saviola": 89,
    "Juan Pablo Sorín": 90,
    "Javier Mascherano": 87,
    "Esteban Cambiasso": 88,
    "Juan Román Riquelme": 94,
    "Hernán Crespo": 93,
    "Maxi Rodríguez": 91,
    "Gilberto Silva": 91,
    "Cafu": 92,
    "Roberto Carlos": 94,
    "Lúcio": 93,
    "Juan": 84,
    "Emerson": 89,
    "Kaká": 94,
    "Ronaldo": 94,
    "Adriano": 91,
    "Ricardo": 91,
    "Paulo Ferreira": 89,
    "Ricardo Carvalho": 94,
    "Fernando Meira": 86,
    "Nuno Valente": 88,
    "José Francisco Porras": 87,
    "Maniche": 91,
    "Deco": 94,
    "Cristiano Ronaldo": 91,
    "Luís Figo": 92,
    "Miguel": 91,
    "Iker Casillas": 91,
    "Sergio Ramos": 90,
    "Carles Puyol": 93,
    "Mariano Pernía": 86,
    "Xavi": 91,
    "Xabi Alonso": 90,
    "Cesc Fàbregas": 84,
    "Joaquín": 87,
    "David Villa": 93,
    "Fernando Torres": 91,
    "Fabien Barthez": 88,
    "Lilian Thuram": 92,
    "William Gallas": 91,
    "Eric Abidal": 88,
    "Patrice Evra": 87,
    "Claude Makélélé": 92,
    "Patrick Vieira": 93,
    "Franck Ribéry": 88,
    "Zinedine Zidane": 96,
    "Thierry Henry": 95,
    "David Trezeguet": 91,
    "Florent Malouda": 89,
    "Gianluigi Buffon": 96,
    "Gianluca Zambrotta": 94,
    "Marco Materazzi": 91,
    "Alessandro Nesta": 93,
    "Fabio Grosso": 89,
    "Andrea Pirlo": 94,
    "Gennaro Gattuso": 92,
    "Daniele De Rossi": 88,
    "Francesco Totti": 94,
    "Alessandro Del Piero": 92,
    "Luca Toni": 94,
    "Vincenzo Iaquinta": 87,
    "Edwin van der Sar": 93,
    "John Heitinga": 86,
    "Joris Mathijsen": 87,
    "André Ooijer": 85,
    "Giovanni van Bronckhorst": 89,
    "Mark van Bommel": 89,
    "Wesley Sneijder": 87,
    "Rafael van der Vaart": 87,
    "Arjen Robben": 92,
    "Rutgerus Johannes Martinus van Nistelrooij": 93,
    "Dirk Kuyt": 88,
    "Robin van Persie": 89,
    "Paul Robinson": 89,
    "Gary Neville": 89,
    "Rio Ferdinand": 92,
    "John Terry": 94,
    "Ashley Cole": 92,
    "Frank Lampard": 94,
    "Steven Gerrard": 94,
    "David Beckham": 91,
    "Joe Cole": 89,
    "Wayne Rooney": 91,
    "Michael Owen": 88,
    "Peter Crouch": 85,
    "Petr Čech": 94,
    "Zdeněk Grygera": 86,
    "Tomáš Ujfaluši": 89,
    "Jan Koller": 89,
    "Tomáš Rosický": 91,
    "Pavel Nedvěd": 92,
    "Tomáš Galásek": 87,
    "Jaroslav Plašil": 84,
    "Jan Polák": 84,
    "Milan Baroš": 89,
    "Karel Poborský": 88,
    "Vratislav Lokvenc": 83,
    "Oswaldo Sánchez": 90,
    "Ricardo Osorio": 88,
    "Rafael Márquez": 92,
    "Carlos Salcido": 89,
    "Francisco Javier Rodríguez": 84,
    "Pável Pardo": 89,
    "Gerardo Torrado": 87,
    "Ramón Morales": 86,
    "Jared Borgetti": 89,
    "Omar Bravo": 88,
    "Francisco Fonseca": 84
  },
  2010: {
    "Iker Casillas": 94,
    "Sergio Ramos": 93,
    "Carles Puyol": 94,
    "Gerard Piqué": 91,
    "Joan Capdevila": 88,
    "Sergio Busquets": 90,
    "Xabi Alonso": 91,
    "Xavi": 96,
    "Andrés Iniesta": 96,
    "David Villa": 96,
    "Fernando Torres": 91,
    "Júlio César": 94,
    "Maicon": 95,
    "Lúcio": 93,
    "Juan": 90,
    "Michel Bastos": 87,
    "Gilberto Silva": 88,
    "Felipe Melo": 86,
    "Kaká": 91,
    "Robinho": 90,
    "Luís Fabiano": 93,
    "Elano": 87,
    "Hugo Lloris": 91,
    "Bacary Sagna": 89,
    "William Gallas": 88,
    "Eric Abidal": 89,
    "Patrice Evra": 91,
    "Jérémy Toulalan": 86,
    "Florent Malouda": 90,
    "Franck Ribéry": 91,
    "Yoann Gourcuff": 87,
    "Sidney Govou": 83,
    "Nicolas Anelka": 88,
    "Gianluigi Buffon": 93,
    "Giorgio Chiellini": 92,
    "Fabio Cannavaro": 91,
    "Leonardo Bonucci": 84,
    "Gianluca Zambrotta": 89,
    "Daniele De Rossi": 91,
    "Andrea Pirlo": 92,
    "Claudio Marchisio": 86,
    "Antonio Di Natale": 90,
    "Vincenzo Iaquinta": 85,
    "Fabio Quagliarella": 87,
    "Maarten Stekelenburg": 91,
    "Gregory van der Wiel": 87,
    "John Heitinga": 88,
    "Joris Mathijsen": 88,
    "Giovanni van Bronckhorst": 89,
    "Nigel de Jong": 89,
    "Mark van Bommel": 91,
    "Wesley Sneijder": 96,
    "Arjen Robben": 94,
    "Robin van Persie": 91,
    "Dirk Kuyt": 89,
    "Manuel Neuer": 90,
    "Philipp Lahm": 92,
    "Per Mertesacker": 88,
    "Arne Friedrich": 87,
    "Holger Badstuber": 84,
    "Bastian Schweinsteiger": 93,
    "Sami Khedira": 87,
    "Mesut Özil": 91,
    "Thomas Müller": 93,
    "Miroslav Klose": 94,
    "Lukas Podolski": 89,
    "Eduardo": 86,
    "Pepe": 91,
    "Ricardo Carvalho": 91,
    "Bruno Alves": 90,
    "Fábio Coentrão": 86,
    "Raul Meireles": 88,
    "Tiago": 85,
    "Deco": 88,
    "Pedro": 87,
    "Cristiano Ronaldo": 96,
    "Liédson": 88,
    "Jorge Valdivia": 84,
    "Ricardo Osorio": 87,
    "Rafael Márquez": 88,
    "Héctor Moreno": 82,
    "Francisco Javier Rodríguez": 84,
    "Gerardo Torrado": 87,
    "Giovani dos Santos": 84,
    "Pablo Barrera": 82,
    "Javier Hernández": 88,
    "Cuauhtémoc Blanco": 84,
    "Fernando Muslera": 89,
    "Diego Godín": 88,
    "Diego Lugano": 91,
    "Maxi Pereira": 88,
    "Martín Cáceres": 85,
    "Egidio Arévalo Ríos": 87,
    "Diego Pérez": 85,
    "Diego Forlán": 96,
    "Luis Suárez": 91,
    "Edinson Cavani": 87,
    "Sebastián Abreu": 84
  },
  2014: {
    "Manuel Neuer": 95,
    "Philipp Lahm": 94,
    "Cristiano Ronaldo": 96,
    "Jérôme Boateng": 91,
    "Mats Hummels": 94,
    "Benedikt Höwedes": 88,
    "Bastian Schweinsteiger": 94,
    "Toni Kroos": 94,
    "Mesut Özil": 92,
    "Thomas Müller": 96,
    "Miroslav Klose": 91,
    "Marco Ureña": 82,
    "Júlio César": 88,
    "Dani Alves": 91,
    "Thiago Silva": 94,
    "David Luiz": 91,
    "Marcelo": 92,
    "Luiz Gustavo": 88,
    "Paulinho": 87,
    "Ramires": 86,
    "Willian": 90,
    "Neymar": 96,
    "Fred": 82,
    "Hugo Lloris": 93,
    "Mathieu Debuchy": 84,
    "Raphaël Varane": 89,
    "Mamadou Sakho": 86,
    "Patrice Evra": 89,
    "Paul Pogba": 92,
    "Blaise Matuidi": 91,
    "Mathieu Valbuena": 89,
    "Karim Benzema": 94,
    "Antoine Griezmann": 87,
    "Olivier Giroud": 88,
    "Claudio Bravo": 91,
    "Gary Medel": 89,
    "Gonzalo Jara": 85,
    "Charles Aránguiz": 88,
    "Arturo Vidal": 94,
    "Marcelo Díaz": 87,
    "Jorge Valdivia": 88,
    "Alexis Sánchez": 95,
    "Eduardo Vargas": 88,
    "Jean Beausejour": 85,
    "Mauricio Pinilla": 84,
    "Fernando Muslera": 91,
    "Diego Godín": 94,
    "José Giménez": 83,
    "Martín Cáceres": 87,
    "Maxi Pereira": 88,
    "Álvaro González": 85,
    "Egidio Arévalo Ríos": 88,
    "Nicolás Lodeiro": 85,
    "Edinson Cavani": 92,
    "Luis Suárez": 97,
    "Diego Forlán": 87,
    "Keylor Navas": 91,
    "Óscar Duarte": 85,
    "Giancarlo González": 87,
    "Michael Umaña": 84,
    "Júnior Díaz": 82,
    "Celso Borges": 87,
    "Yeltsin Tejeda": 82,
    "Bryan Ruiz": 89,
    "Joel Campbell": 88,
    "Christian Bolaños": 84,
    "Guillermo Ochoa": 92,
    "Paul Aguilar": 85,
    "Héctor Herrera": 89,
    "Rafael Márquez": 89,
    "Miguel Layún": 87,
    "José Juan Vázquez": 84,
    "Andrés Guardado": 88,
    "Giovani dos Santos": 85,
    "Javier Hernández": 88,
    "Oribe Peralta": 89,
    "Matthew Spiranovic": 90,
    "DaMarcus Beasley": 84,
    "Geoff Cameron": 85,
    "Matt Besler": 84,
    "Jermaine Jones": 86,
    "Michael Bradley": 89,
    "Clint Dempsey": 91,
    "Graham Zusi": 82,
    "Fabian Johnson": 84,
    "Jozy Altidore": 83,
    "Aron Jóhannsson": 80
  },
  2018: {
    "Hugo Lloris": 93,
    "Benjamin Pavard": 88,
    "Raphaël Varane": 93,
    "Samuel Umtiti": 92,
    "Lucas Hernandez": 87,
    "N'Golo Kanté": 94,
    "Paul Pogba": 92,
    "Kylian Mbappé": 94,
    "Antoine Griezmann": 96,
    "Olivier Giroud": 91,
    "Corentin Tolisso": 86,
    "Alisson": 93,
    "Danilo": 86,
    "Thiago Silva": 93,
    "Miranda": 89,
    "Marcelo": 92,
    "Carlos Sánchez": 92,
    "Paulinho": 87,
    "Willian": 91,
    "Philippe Coutinho": 94,
    "Neymar": 95,
    "Gabriel Jesus": 88,
    "Thibaut Courtois": 95,
    "Toby Alderweireld": 91,
    "Vincent Kompany": 90,
    "Jan Vertonghen": 92,
    "Thomas Meunier": 89,
    "Kevin De Bruyne": 96,
    "Axel Witsel": 89,
    "Yannick Carrasco": 86,
    "Eden Hazard": 96,
    "Romelu Lukaku": 94,
    "Dries Mertens": 89,
    "Manuel Neuer": 91,
    "Joshua Kimmich": 91,
    "Jérôme Boateng": 89,
    "Antonio Rüdiger": 87,
    "Jonas Hector": 85,
    "Toni Kroos": 93,
    "Sami Khedira": 87,
    "Mesut Özil": 89,
    "Thomas Müller": 89,
    "Timo Werner": 86,
    "Marco Reus": 89,
    "David de Gea": 91,
    "Jordi Alba": 92,
    "Sergio Ramos": 94,
    "Gerard Piqué": 91,
    "José Ignacio Fernández Iglesias": 87,
    "Sergio Busquets": 92,
    "Thiago": 89,
    "David Silva": 93,
    "Isco": 92,
    "Diego Costa": 90,
    "Marco Asensio": 86,
    "Se-jong Ju": 85,
    "Robin Olsen": 86,
    "Mathew Ryan": 83,
    "Rui Patrício": 91,
    "Raphaël Guerreiro": 87,
    "Pepe": 91,
    "José Fonte": 87,
    "João Mário": 86,
    "William Carvalho": 87,
    "João Moutinho": 88,
    "Bernardo Silva": 89,
    "Cristiano Ronaldo": 98,
    "Ricardo Quaresma": 88,
    "André Silva": 82,
    "Guillermo Ochoa": 91,
    "Héctor Moreno": 87,
    "Javier Hernández": 87,
    "Javier Aquino": 83,
    "Héctor Herrera": 88,
    "Jonathan dos Santos": 84,
    "Marco Fabián": 82,
    "Jesús Gallardo": 83,
    "Carlos Vela": 88,
    "Hirving Lozano": 89,
    "Raúl Jiménez": 86
  },
  2022: {
    "Emiliano Martínez": 94,
    "Nahuel Molina": 88,
    "Cristian Romero": 91,
    "Nicolás Otamendi": 91,
    "Marcos Acuña": 91,
    "Rodrigo De Paul": 91,
    "Enzo Fernández": 92,
    "Alexis Mac Allister": 90,
    "Ángel Di María": 91,
    "Lionel Messi": 99,
    "Julián Álvarez": 91,
    "Alisson": 93,
    "Danilo": 87,
    "Thiago Silva": 92,
    "Alex Sandro": 86,
    "Carlos Martínez": 94,
    "Lucas Tolentino Coelho de Lima": 89,
    "Raphaël Varane": 92,
    "Richarlison": 89,
    "Neymar": 96,
    "Vinícius Júnior": 95,
    "Hugo Lloris": 92,
    "Jules Koundé": 89,
    "Dayot Upamecano": 88,
    "Théo Hernandez": 91,
    "Aurélien Tchouaméni": 89,
    "Adrien Rabiot": 89,
    "Ousmane Dembélé": 91,
    "Antoine Griezmann": 95,
    "Kylian Mbappé": 98,
    "Olivier Giroud": 92,
    "Jordan Pickford": 90,
    "Kieran Trippier": 87,
    "John Stones": 90,
    "Harry Maguire": 87,
    "Luke Shaw": 87,
    "Declan Rice": 90,
    "Jude Bellingham": 92,
    "Phil Foden": 90,
    "Harry Kane": 96,
    "Raheem Sterling": 87,
    "Bukayo Saka": 91,
    "Thibaut Courtois": 95,
    "Thomas Meunier": 86,
    "Jan Vertonghen": 88,
    "Timothy Castagne": 85,
    "Arthur Theate": 84,
    "Youri Tielemans": 86,
    "Leandro Trossard": 88,
    "Kevin De Bruyne": 96,
    "Eden Hazard": 84,
    "Romelu Lukaku": 88,
    "Michy Batshuayi": 84,
    "Robert Sánchez": 78,
    "David Raya": 81,
    "Unai Simón": 86,
    "César Azpilicueta": 84,
    "Eric García": 78,
    "Pau Torres": 84,
    "Alejandro Balde": 82,
    "Hugo Guillamón": 76,
    "Jordi Alba": 88,
    "Dani Carvajal": 87,
    "Aymeric Laporte": 88,
    "Sergio Busquets": 91,
    "Marcos Llorente": 86,
    "Jorge Sánchez": 83,
    "Gavi": 82,
    "Rodri": 91,
    "Carlos Soler": 82,
    "Pedro": 91,
    "Álvaro Morata": 88,
    "Marco Asensio": 84,
    "Ferran Torres": 84,
    "Nico Williams": 80,
    "Yeremy Pino": 79,
    "Pablo Sarabia": 84,
    "Ansu Fati": 80,
    "William Saliba": 88,
    "Ibrahima Konaté": 87,
    "Benjamin Pavard": 87,
    "Eduardo Camavinga": 86,
    "Kingsley Coman": 89,
    "Christopher Wooh": 87,
    "Marcus Thuram": 84,
    "Randal Kolo Muani": 88,
    "Diogo Costa": 89,
    "João Cancelo": 91,
    "Rúben Dias": 91,
    "Pepe": 89,
    "Raphaël Guerreiro": 87,
    "William Carvalho": 84,
    "Bruno Fernandes": 92,
    "Bernardo Silva": 94,
    "João Félix": 87,
    "Cristiano Ronaldo": 90,
    "Rafael Leão": 91,
    "Édouard Mendy": 84,
    "Kalidou Koulibaly": 90,
    "Abdou Diallo": 84,
    "Youssouf Sabaly": 84,
    "Fodé Ballo-Touré": 82,
    "Idrissa Gueye": 85,
    "Cheikhou Kouyaté": 82,
    "Ismaïla Sarr": 85,
    "Famara Diédhiou": 82,
    "Yassine Bounou": 92,
    "Achraf Hakimi": 92,
    "Romain Saïss": 88,
    "Nayef Aguerd": 87,
    "Noussair Mazraoui": 88,
    "Sofyan Amrabat": 91,
    "Azzedine Ounahi": 87,
    "Hakim Ziyech": 89,
    "Abdelhamid Sabiri": 83,
    "Youssef En-Nesyri": 87,
    "Sofiane Boufal": 87,
    "Manuel Neuer": 90,
    "Antonio Rüdiger": 91,
    "Niklas Süle": 85,
    "David Raum": 84,
    "Joshua Kimmich": 91,
    "Leon Goretzka": 88,
    "İlkay Gündoğan": 90,
    "Serge Gnabry": 87,
    "Leroy Sané": 89,
    "Thomas Müller": 87,
    "Kai Havertz": 87,
    "Jurriën Timber": 85,
    "Matthijs de Ligt": 88,
    "Virgil van Dijk": 94,
    "Denzel Dumfries": 89,
    "Frenkie de Jong": 92,
    "Teun Koopmeiners": 86,
    "Cody Gakpo": 90,
    "Steven Bergwijn": 85,
    "Memphis Depay": 90,
    "Daley Blind": 85,
    "Guillermo Ochoa": 87,
    "Héctor Moreno": 84,
    "César Montes": 84,
    "Johan Vásquez": 82,
    "Edson Álvarez": 88,
    "Héctor Herrera": 83,
    "Orbelín Pineda": 82,
    "Hirving Lozano": 88,
    "Alexis Vega": 84,
    "Henry Martín": 84
  },
  2026: {
    "Alisson Ramses Becker": 94,
    "Danilo dos Santos de Oliveira": 87,
    "Marcos Aoás Corrêa": 92,
    "Gabriel dos Santos Magalhães": 91,
    "Alex Sandro Lobo Silva": 86,
    "Carlos Henrique Casimiro": 94,
    "Bruno Guimarães Rodrigues Moura": 93,
    "Lucas Tolentino Coelho de Lima": 90,
    "Raphael Dias Belloli": 94,
    "Neymar da Silva Santos Júnior": 95,
    "Vinícius José Paixão de Oliveira Júnior": 98,
    "Emiliano Martínez": 95,
    "Gonzalo Montiel": 88,
    "Cristian Gabriel Romero": 93,
    "Nicolás Hernán Otamendi": 90,
    "Nicolás Tagliafico": 88,
    "Rodrigo Javier De Paul": 91,
    "Enzo Jeremías Fernández": 94,
    "Alexis Mac Allister": 93,
    "Ángel Fabián Di María": 90,
    "Lionel Andrés Messi": 99,
    "Julián Álvarez": 94,
    "Hugo Hadrien Lloris": 92,
    "Jules Olivier Koundé": 91,
    "Dayot Upamecano": 89,
    "Théo Bernard François Hernández": 92,
    "Eduardo Camavinga": 91,
    "Adrien Rabiot": 90,
    "Ousmane Dembélé": 96,
    "Antoine Griezmann": 95,
    "Kylian Mbappé Lottin": 99,
    "Michael Olise": 92,
    "Marc-André ter Stegen": 93,
    "Joshua Walter Kimmich": 94,
    "Antonio Rüdiger": 92,
    "Nico Schlotterbeck": 90,
    "David Raum": 88,
    "Leon Goretzka": 90,
    "İlkay Gündoğan": 91,
    "Jamal Musiala": 97,
    "Florian Wirtz": 96,
    "Serge Gnabry": 90,
    "Kai Lukas Havertz": 91,
    "Unai Simón Mendibil": 93,
    "Pedro González López": 91,
    "Robin Le Normand": 91,
    "Pau Francisco Torres": 90,
    "Alejandro Grimaldo García": 93,
    "Rodri Hernández Cascante": 97,
    "Martín Zubimendi Ibáñez": 91,
    "Pedri González López": 96,
    "Lamine Yamal Nasraoui Ebana": 98,
    "Álvaro Morata Martín": 90,
    "Nico Williams Arthuer": 94,
    "Jordan Lee Pickford": 93,
    "Trent John Alexander-Arnold": 94,
    "John Stones": 92,
    "William Saliba": 94,
    "Lewis Hall": 88,
    "Declan Rice": 94,
    "Jude Victor William Bellingham": 97,
    "Phil Foden": 96,
    "Bukayo Saka": 95,
    "Harry Edward Kane": 97,
    "Anthony Gordon": 90,
    "Diogo Meireles Costa": 92,
    "João Pedro Cavaco Cancelo": 92,
    "Rúben dos Santos Gato Alves Dias": 93,
    "António João Tavares Silva": 90,
    "Raphaël Adelino José Guerreiro": 88,
    "João Maria Lobo Alves Palhinha Gonçalves": 91,
    "Bruno Miguel Borges Fernandes": 96,
    "Bernardo Mota Veiga de Carvalho e Silva": 96,
    "Rafael Alexandre da Conceição Leão": 94,
    "João Félix Sequeira": 91,
    "Cristiano Ronaldo dos Santos Aveiro": 96,
    "Bart Verbruggen": 92,
    "Denzel Justus Morris Dumfries": 91,
    "Virgil van Dijk": 95,
    "Matthijs de Ligt": 91,
    "Jorrel Hato": 88,
    "Frenkie de Jong": 95,
    "Tijjani Reijnders": 93,
    "Xavi Quentin Shay Simons": 93,
    "Cody Mathès Gakpo": 94,
    "Memphis Depay": 92,
    "Jeremie Agyekum Frimpong": 91,
    "Thibaut Nicolas Marc Courtois": 96,
    "Timothy Castagne": 87,
    "Arthur Nicolas Theate": 88,
    "Zeno Debast": 87,
    "Maxim De Cuyper": 88,
    "Youri Tielemans": 91,
    "Amadou Onana": 90,
    "Kevin De Bruyne": 97,
    "Jérémy Doku": 93,
    "Romelu Lukaku": 94,
    "Leandro Trossard": 91,
    "Sergio Rochet Álvarez": 91,
    "Guillermo Sebastián Varela Olivera": 87,
    "Ronald Federico Araújo da Silva": 94,
    "José María Giménez de Vargas": 91,
    "Matías Viña Susperreguy": 87,
    "Federico Santiago Valverde Dipetta": 96,
    "Manuel Ugarte Ribeiro": 91,
    "Rodrigo Bentancur Colmán": 90,
    "Facundo Pellistri Rebollo": 88,
    "Darwin Gabriel Núñez Ribeiro": 94,
    "Luis Alberto Suárez Díaz": 90
  }
};
